[db]
port = 54322
major_version = 15

[studio]
port = 9096

[auth]
site_url = "http://localhost:9098"
additional_redirect_urls = ["http://localhost:9098"]

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
