import type { CodeSprite } from '../../../src/draw';

/** Foreman Grask: a hulking cave troll in a lantern helmet, fists like boulders. */
const grask: CodeSprite = {
  size: 32,
  legend: {
    k: '#181425',
    g: '#8b9bb4',
    G: '#5a6988',
    d: '#3a4466',
    m: '#265c42',
    M: '#3e8948',
    l: '#63c74d',
    y: '#fee761',
    Y: '#feae34',
    h: '#be4a2f',
    H: '#d77643',
    e: '#f77622',
    b: '#733e39',
    B: '#3e2731',
    t: '#ead4aa',
  },
  mirror: true,
  frames: [
    [
      '..........kkkkkk',
      '........kkHHHyyy',
      '.......khHHHHyYY',
      '......khhHHHHHyk',
      '......kkkkkkkkkk',
      '.....kmmMMMMMMMM',
      '.....kmMMlMMMMMM',
      '.....kmMkeMMMMMM',
      '.....kmMMMMMMMMM',
      '......kmMMtMMMtM',
      '......kmmMkkkkkk',
      '...kkkkmmmMMMMMM',
      '..kmMMMkmmmMMMMM',
      '.kmMlMMMkbbbbbbb',
      '.kmMMMMMkbBBBBbY',
      'kmMMMMMMkbbbbbbb',
      'kmMMMMMmkmmMMMMM',
      'kmmMMMmkkmmmMMMM',
      '.kmmmmkkmmmmMMMM',
      '.kGGGGkkmmmmmMMM',
      'kGggggGkkmmmmmMM',
      'kGgggggGkkmmmmmm',
      'kGGgggGGk.kkkmmm',
      '.kGGGGGk..kbbbbb',
      '..kkkkk..kbbBBbb',
      '........kbbBBBbk',
      '........kmmmmmk.',
      '.......kmMMMMmk.',
      '.......kkkkkkk..',
    ],
  ],
};

export default grask;
