import type { CodeSprite } from '../../../src/draw';

/** Hesta, the Anvil-keeper: an ember-haired smith in a leather apron, her hammer idle, then lifted. */
const hesta: CodeSprite = {
  size: 26,
  legend: {
    k: '#181425',
    h: '#be4a2f',
    j: '#f77622',
    f: '#e8b796',
    F: '#c28569',
    s: '#ead4aa',
    S: '#e4a672',
    a: '#b86f50',
    A: '#733e39',
    b: '#3e2731',
    w: '#733e39',
    m: '#c0cbdc',
    M: '#8b9bb4',
    n: '#5a6988',
    g: '#feae34',
  },
  idle: 'none',
  frames: [
    [
      '......kkkk............',
      '.....khjhhk...........',
      '....kkhhhhkk..........',
      '...khjjhhhhhk.........',
      '...khjffffhhk.........',
      '...khfkffkfhk.kkkkkkkk',
      '...khffffffFk.kmmMMMnk',
      '....kFffffFk..kMMMMnnk',
      '..kssskFFkssskknnnnnnk',
      '.ksssAaaaaAssskkkwkkkk',
      'kssSkAaaaaAkSssk.kwk..',
      'kfFkaaaaaaaakFfkkwk...',
      'kffkaaaaaaaAkffffwfk..',
      'kFFkAAAggAAAkFFFFwFk..',
      'kffkaaaaaaaAkkkkkwk...',
      '.kkkaaaaaaaAk....k....',
      '...kaaaaaaaAk.........',
      '...kAAAAAAAAk.........',
      '...kbbbkkbbbk.........',
      '...kbbbkkbbbk.........',
      '..kAAAAkkAAAAk........',
      '..kkkkkkkkkkkk........',
    ],
    [
      '..............kkkkkkkk',
      '..............kmmMMMnk',
      '..............kMMMMnnk',
      '..............knnnnnnk',
      '......kkkk....kkkwkkkk',
      '.....khjhhk.....kwk...',
      '....kkhhhhkk...kfwfk..',
      '...khjjhhhhhk..kfwfk..',
      '...khjffffhhk..kFFFk..',
      '...khfkffkfhk.kfFk....',
      '...khffffffFk.kfFk....',
      '....kFffffFk.kssk.....',
      '..kssskFFksssssk......',
      '.ksssAaaaaAsssk.......',
      'kssSkAaaaaAsk.........',
      'kfFkaaaaaaaak.........',
      'kffkaaaaaaaAk.........',
      'kFFkAAAggAAAk.........',
      'kffkaaaaaaaAk.........',
      '.kkkaaaaaaaAk.........',
      '...kaaaaaaaAk.........',
      '...kAAAAAAAAk.........',
      '...kbbbkkbbbk.........',
      '...kbbbkkbbbk.........',
      '..kAAAAkkAAAAk........',
      '..kkkkkkkkkkkk........',
    ],
  ],
};

export default hesta;
